version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.16.0   # Specify the desired Node.js version
    commands:
      - npm install

build:
  commands:
    - npm run build

artifacts:
  files:
    - '**/*'
